import logoUrl from "@/assets/images/sqldesk_icon.svg";

/*
  Lays the captured dashboard onto a branded page.

  Composited on a canvas rather than by cloning the DOM and capturing that.
  A clone loses the contents of any <canvas> a visualisation drew into —
  cloneNode copies the element, not its bitmap — so chart widgets would come
  out blank. Capturing the live DOM first and drawing the result keeps
  whatever html-to-image already resolved.
*/

// Page furniture, in CSS pixels; multiplied by the capture scale below so
// the header is as sharp as the dashboard beside it.
const MARGIN = 40;
const HEADER_HEIGHT = 64;
const LOGO_SIZE = 30;

function loadImage(src) {
  return new Promise((resolve, reject) => {
    const image = new Image();
    image.onload = () => resolve(image);
    image.onerror = () => reject(new Error(`Could not load ${src}`));
    image.src = src;
  });
}

function readToken(name, fallback) {
  const value = getComputedStyle(document.documentElement).getPropertyValue(name).trim();
  return value || fallback;
}

export default async function composeExportCanvas({
  dashboardImage,
  title,
  owner,
  generatedBy,
  generatedAt,
  scale = 2,
}) {
  // Without this the header can be drawn in a fallback face while the
  // webfont is still loading, so the export would not match the app.
  if (document.fonts && document.fonts.ready) {
    await document.fonts.ready;
  }

  const margin = MARGIN * scale;
  const headerHeight = HEADER_HEIGHT * scale;

  const canvas = document.createElement("canvas");
  canvas.width = dashboardImage.width + margin * 2;
  canvas.height = dashboardImage.height + headerHeight + margin * 2;

  const ctx = canvas.getContext("2d");

  // The same off-white the app uses, so an exported page reads as part of
  // the product rather than a screenshot on white.
  ctx.fillStyle = readToken("--color-canvas", "#fbfaf9");
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  const sans = '"Instrument Sans Variable", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';
  const baseline = margin + headerHeight / 2;

  let cursor = margin;

  try {
    const logo = await loadImage(logoUrl);
    const size = LOGO_SIZE * scale;
    ctx.drawImage(logo, cursor, baseline - size / 2, size, size);
    cursor += size + 12 * scale;
  } catch (error) {
    // A missing logo should not cost the user their export.
    cursor = margin;
  }

  ctx.textBaseline = "middle";

  ctx.font = `600 ${17 * scale}px ${sans}`;
  ctx.fillStyle = readToken("--color-text", "#1c1b1a");
  ctx.fillText("SQLDesk", cursor, baseline);
  cursor += ctx.measureText("SQLDesk").width + 12 * scale;

  /*
    Provenance, right-aligned on the same band. Drawn BEFORE the dashboard
    name so the space it occupies is known: a long name and three long
    fields would otherwise overlap in the middle, and the name is the part
    that can be truncated without losing meaning.
  */
  const labelFont = `500 ${12 * scale}px ${sans}`;
  const valueFont = `600 ${12 * scale}px ${sans}`;
  const mutedInk = readToken("--color-text-muted", "#6f6b66");
  const primaryInk = readToken("--color-text", "#1c1b1a");

  const fields = [
    owner && { label: "Owner", value: owner },
    generatedBy && { label: "Generated by", value: generatedBy },
    generatedAt && { label: "Generated at", value: generatedAt },
  ].filter(Boolean);

  let rightEdge = canvas.width - margin;
  fields
    .slice()
    .reverse()
    .forEach((field) => {
      ctx.font = valueFont;
      const valueWidth = ctx.measureText(field.value).width;
      ctx.font = labelFont;
      const labelWidth = ctx.measureText(`${field.label}: `).width;

      const blockStart = rightEdge - valueWidth - labelWidth;
      ctx.fillStyle = mutedInk;
      ctx.fillText(`${field.label}: `, blockStart, baseline);
      ctx.font = valueFont;
      ctx.fillStyle = primaryInk;
      ctx.fillText(field.value, blockStart + labelWidth, baseline);

      rightEdge = blockStart - 20 * scale;
    });

  if (title) {
    ctx.fillStyle = readToken("--color-border", "#e8e5e1");
    ctx.fillRect(cursor, baseline - 10 * scale, 1 * scale, 20 * scale);
    cursor += 12 * scale;

    ctx.font = `500 ${17 * scale}px ${sans}`;
    ctx.fillStyle = mutedInk;
    ctx.fillText(truncateToWidth(ctx, title, rightEdge - cursor), cursor, baseline);
  }

  ctx.drawImage(dashboardImage, margin, margin + headerHeight);

  return canvas;
}

// Canvas has no text overflow, so a name longer than its lane silently draws
// over whatever is beside it.
function truncateToWidth(ctx, text, maxWidth) {
  if (maxWidth <= 0 || ctx.measureText(text).width <= maxWidth) {
    return text;
  }
  let result = text;
  while (result.length > 1 && ctx.measureText(`${result}…`).width > maxWidth) {
    result = result.slice(0, -1);
  }
  return `${result}…`;
}
